title: FREx
lang: en
description: This is the main page for the Framework for Recommendations with Explanations (FREx).


# Build settings
remote_theme: rundocs/jekyll-rtd-theme


readme_index:
  with_frontmatter: true

